### ISSUE TITLE
Github Pages layout broken

### ISSUE THREAD

**Issue by hanchangyo** [turtlebot/turtlebot4-user-manual#42]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

not an hardware issue

### Expected behaviour

should show pages in a correct layout, with menus on the left side and contents on the right side.

### Actual behaviour

<img width="572" height="1032" alt="Image" src="https://github.com/user-attachments/assets/997340ac-9c41-46e8-bbc5-49fd52e2adc9" />

When I access the manual page, the layout is completeley broken.

### Error messages

```bash

```

### To Reproduce

access the page

**Comment by mohamedtahaguelzim** [comment]
I cloned the repo and built locally, and the layout seems fine. The issue will probably be fixed by rebuilding and redeploying correctly the repo.
edit: which means that the issue is probably due to the build/deploy workflow.

**Comment by tonybaltovski** [comment]
@mohamedtahaguelzim I had the same experience where it built fine locally.  I fixed a warning in the CI and updated some the action which should have re-deployed the site but it still isn't displaying correctly.

**Comment by tonybaltovski** [comment]
Looks like @hilary-luo changes fixed this.
